### ISSUE TITLE
regquery: cannot stat 'etc/apache2/sites-available/nmos-api-query.conf'

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [bbc/nmos-discovery-registration-ri#4]
When I do "vagrant up" I get this:

```
==> regquery: cp: 
==> regquery: cannot stat 'etc/apache2/sites-available/nmos-api-query.conf'
==> regquery: : No such file or directory
==> regquery: Failed to start nmosquery.service: Unit nmosquery.service not found.
==> regquery: apache2: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

And then if I try this, the curl fails:

```
$ vagrant ssh regquery
...
vagrant@regquery:~$ curl --noproxy localhost localhost/x-nmos/query/v1.1/nodes/
curl: (7) Failed to connect to localhost port 80: Connection refused
```

Note that:

```
vagrant@regquery:~$ ls /etc/apache2
ls: cannot access '/etc/apache2': No such file or directory
```

**Comment by andrewbonney** [comment]
Thanks for the report. My suspicion is that we have an error in the shell scripts where they install a reverse proxy package. This should probably read:

```
dpkg -i ../ips-reverseproxy-common_*_all.deb
```

rather than...

```
dpkg -i ../nmos-reverse-proxy_*_all.deb
```

On lines 60 in provision_node.sh and 59 in provision_query.sh.

We'll test this out locally and push a fix to master if that resolves things, but please feel free to try that in your own local copy too.

**Comment by andrewbonney** [comment]
After some slight internal confusion, it's been noted that this is no longer the correct repository to be using to build the reference implementation. The correct URL is: https://github.com/bbc/nmos-joint-ri

In theory external links to this repository should have been updated to point at the new one, but in case they haven't I'll push a new version of this repo which contains just a README pointing at the new location.
